# Generated by Django 5.1.15 on 2026-10-02 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_installmentplan_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('document', 'Document'), ('other', 'Other')], default='receipt', max_length=12)),
                ('file_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(blank=True, max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('size', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
