# Generated by Django 5.1.15 on 2026-10-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_installmentplan_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.debt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.savingsgoal'),
        ),
    ]
