# Generated by Django 5.1.15 on 2026-10-02 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('op', models.CharField(max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_mutation_id', models.CharField(max_length=64)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('op', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], max_length=10)),
                ('server_version', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client_mutation_id')},
            },
        ),
    ]
