# Generated by Django 5.1.15 on 2026-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmutation',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
